       </td>
      </tr></tbody></table>
     </font></center>
    </div>
   </td>
  </tr><tr>
  <td colSpan=5 height=20 width="805" style="background-repeat: repeat-y;">
   <p align=center><font face="黑体" size="2"></a><a href="http://www.skuo.com.cn">浙江西谷数字技术有限公司</a> 
    版权所有</font></p>
	<p align=center><font face="黑体" size="2"><a href="http://www.skuo.com.cn/lxwm/">联系我们</a>
	</font></p>
  </td>
 </tr></tbody></table>
</div></body>
</html>
